#!/usr/bin/env node

var fs = require('fs'),
    exec = require('child_process').exec,
    path = require('path'),
    glob = require('glob');

var packages = glob.sync('turf_modules/turf-*/package.json').map(function(pkg) {
  return [pkg, JSON.parse(fs.readFileSync(pkg))];
});

var latest = packages.reduce(function(memo, pkg) {
    memo[pkg[1].name] = pkg[1].version;
    return memo;
}, {});

var updated = packages.map(function(p) {
    var pkg = p[1];
    var k;
    for (k in pkg.dependencies) {
        if (latest[k]) {
            pkg.dependencies[k] = '^' + latest[k];
        }
    }
    for (k in pkg.devDependencies) {
        if (latest[k]) {
            pkg.devDependencies[k] = '^' + latest[k];
        }
    }
    fs.writeFileSync(p[0], JSON.stringify(pkg, null, 2));
});
